// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe-YjLqjQgAmXmzQzFweeFLoXKdId7v6w',
    appId: '1:556248166395:web:f2cbe97fe6c1034cb2e55e',
    messagingSenderId: '556248166395',
    projectId: 'team007-dc442',
    storageBucket: 'gs://team007-dc442.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe-YjLqjQgAmXmzQzFweeFLoXKdId7v6w',
    appId: '1:556248166395:web:f2cbe97fe6c1034cb2e55e',
    messagingSenderId: '556248166395',
    projectId: 'team007-dc442',
    storageBucket: 'gs://team007-dc442.appspot.com',
    androidClientId: '404605075093-3bm358s41cl43nsqattq1hqqp462t95d.apps.googleusercontent.com',
    iosClientId: '404605075093-u3346ldaqpto0jej0295hrbcvo9dqcr8.apps.googleusercontent.com',
    iosBundleId: 'com.example.rabloMobile',
  );
}
